// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenalSystem.Infra.Data.Context;

#nullable disable

namespace PenalSystem.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PenalSystem.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<Guid>("PrisonerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrisonerId");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Birth Date");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("E-mail");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.Prisoner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("Arrival Date");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Birth Date");

                    b.Property<int>("BookCounter")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Books Counter");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF")
                        .IsFixedLength();

                    b.Property<int>("CurrentYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Current Year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<DateTime>("OriginalReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Original Release Date");

                    b.Property<DateTime>("UpdatedReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Updated Release Date");

                    b.HasKey("Id");

                    b.ToTable("Prisoners", (string)null);
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.Study", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrisonerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Subject");

                    b.HasKey("Id");

                    b.HasIndex("PrisonerId");

                    b.ToTable("Studies", (string)null);
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.WorkDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<Guid>("PrisonerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrisonerId");

                    b.ToTable("DaysOfWork", (string)null);
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.Book", b =>
                {
                    b.HasOne("PenalSystem.Domain.Entities.Prisoner", "Prisoner")
                        .WithMany("Books")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.Study", b =>
                {
                    b.HasOne("PenalSystem.Domain.Entities.Prisoner", "Prisoner")
                        .WithMany("Studies")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.WorkDay", b =>
                {
                    b.HasOne("PenalSystem.Domain.Entities.Prisoner", "Prisoner")
                        .WithMany("DaysOfWork")
                        .HasForeignKey("PrisonerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prisoner");
                });

            modelBuilder.Entity("PenalSystem.Domain.Entities.Prisoner", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("DaysOfWork");

                    b.Navigation("Studies");
                });
#pragma warning restore 612, 618
        }
    }
}
